config/routes.rb
Pain::Application.routes.draw do

  scope "api" do
    resources :diagrams
  end

  root :to => 'home#index'

end

app/models/diagram.rb
class Diagram < ActiveRecord::Base
  attr_accessible :file, :subject_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  # GET /diagrams
  # GET /diagrams.json
  def index
    @diagrams = Diagram.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagrams }
    end
  end

  # GET /diagrams/1
  # GET /diagrams/1.json
  def show
    @diagram = Diagram.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagram }
    end
  end

  # GET /diagrams/new
  # GET /diagrams/new.json
  def new
    @diagram = Diagram.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagram }
    end
  end

  # GET /diagrams/1/edit
  def edit
    @diagram = Diagram.find(params[:id])
  end

  # POST /diagrams
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(params[:diagram])

    respond_to do |format|
      if @diagram.save
        format.html { redirect_to @diagram, notice: 'Diagram was successfully created.' }
        format.json { render json: @diagram, status: :created, location: @diagram }
      else
        format.html { render action: "new" }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagrams/1
  # PUT /diagrams/1.json
  def update
    @diagram = Diagram.find(params[:id])

    respond_to do |format|
      if @diagram.update_attributes(params[:diagram])
        format.html { redirect_to @diagram, notice: 'Diagram was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.json
  def destroy
    @diagram = Diagram.find(params[:id])
    @diagram.destroy

    respond_to do |format|
      format.html { redirect_to diagrams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/diagrams/_form.html.erb
<%= form_for(@diagram) do |f| %>
  <% if @diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagram.errors.count, "error") %> prohibited this diagram from being saved:</h2>

      <ul>
      <% @diagram.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br />
    <%= f.number_field :subject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagrams/edit.html.erb
<h1>Editing diagram</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagram %> |
<%= link_to 'Back', diagrams_path %>

app/views/diagrams/index.html.erb
<h1>Listing diagrams</h1>

<table>
  <tr>
    <th>File</th>
    <th>Subject</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagrams.each do |diagram| %>
  <tr>
    <td><%= diagram.file %></td>
    <td><%= diagram.subject_id %></td>
    <td><%= link_to 'Show', diagram %></td>
    <td><%= link_to 'Edit', edit_diagram_path(diagram) %></td>
    <td><%= link_to 'Destroy', diagram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagram', new_diagram_path %>

app/views/diagrams/new.html.erb
<h1>New diagram</h1>

<%= render 'form' %>

<%= link_to 'Back', diagrams_path %>

app/views/diagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @diagram.file %>
</p>

<p>
  <b>Subject:</b>
  <%= @diagram.subject_id %>
</p>


<%= link_to 'Edit', edit_diagram_path(@diagram) %> |
<%= link_to 'Back', diagrams_path %>

app/views/home/index.html.erb
<%= content_tag "div", "Loading Pain", id: "container", data: { diagrams: Diagram.all() } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pain</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>